# Configuration file for model training parameters

model_training:
    # Random seed for reproducibility
    random_state: 42
    # Pre-trained model checkpoint to use for training
    checkpoint: bert-base-uncased
    # Batch size for training data
    batch_size: 8
    # Number of labels (classes) in the classification task
    num_labels: 2
    # Learning rate for the optimizer
    learning_rate: 5e-5
    # Number of training epochs
    num_epochs: 3
    # Number of warm-up steps for the learning rate scheduler
    num_warmup_steps: 0
